/**
 * 要删的路由(开源 E3 删除域)· 冻结表 —— 单一来源。
 *
 * 取自 OSS_01 J 章 §5(App.tsx 199 条路由逐条归桶,基线 2517095a;行号与现役逐一对上):
 *   C = 废弃-社媒(/s 一族 · /social 一族 · /social-ops 一族 · /social-studio · /public/creator/:shareCode)
 *   D = 废弃-左栏已取消(/c · /m3 两族 + AI 员工 / 顾问团 / Admin AI 可观测性 / 写作长尾 / 发布参谋投放洞察 / 服务商与 Admin 长尾 / 知识库)
 *   另含 App.tsx 里 socialStudioModulePaths 展开出的 /s/<模块> 36 条(静态段胜过在役的 /s/:token,所以必须逐条列出)。
 * 🔴 在役的 `/s/:token`(客户选词报价 SelectionPage)**不在**表里。
 * 🔴 冻结在这里而不是现读 App.tsx:E3 把这些路由从 App.tsx 删掉之后,判据照样认得出「指向已删路由」。
 *
 * 消费方:scripts/test-route-literals-live.mjs(WO_260 S1/S2)· scripts/verify-dead-interactions.mjs(B8 壳链接)
 */
export const RETIRED_ROUTES = [
    ['/public/creator/:shareCode', 'C'],
    ['/s', 'C'],
    ['/s/*', 'C'],
    ['/s/advisor-market', 'C'],
    ['/s/advisors', 'C'],
    ['/s/approval/:token', 'C'],
    ['/s/billing', 'C'],
    ['/s/chat', 'C'],
    ['/s/clients', 'C'],
    ['/s/content-workshop', 'C'],
    ['/s/corpus', 'C'],
    ['/s/creator-profile', 'C'],
    ['/s/data-review', 'C'],
    ['/s/experts', 'C'],
    ['/s/history', 'C'],
    ['/s/home', 'C'],
    ['/s/ideas', 'C'],
    ['/s/imitate', 'C'],
    ['/s/interaction', 'C'],
    ['/s/interaction-management', 'C'],
    ['/s/login', 'C'],
    ['/s/managed', 'C'],
    ['/s/match/:shareCode', 'C'],
    ['/s/my-clients', 'C'],
    ['/s/my-ip', 'C'],
    ['/s/my-profile', 'C'],
    ['/s/operation', 'C'],
    ['/s/persona-setup', 'C'],
    ['/s/plan', 'C'],
    ['/s/planning', 'C'],
    ['/s/profile', 'C'],
    ['/s/research', 'C'],
    ['/s/review', 'C'],
    ['/s/rewrite', 'C'],
    ['/s/scripts', 'C'],
    ['/s/stats', 'C'],
    ['/s/team', 'C'],
    ['/s/topics', 'C'],
    ['/s/trending', 'C'],
    ['/s/video-script', 'C'],
    ['/s/wallet', 'C'],
    ['/s/workshop', 'C'],
    ['/s/writer', 'C'],
    ['/social', 'C'],
    ['/social-ops', 'C'],
    ['/social-ops/advisor-market', 'C'],
    ['/social-ops/advisor-market/chat/:advisorId', 'C'],
    ['/social-ops/corpus', 'C'],
    ['/social-ops/creator-profile', 'C'],
    ['/social-ops/match/:shareCode', 'C'],
    ['/social-ops/my', 'C'],
    ['/social-ops/operation', 'C'],
    ['/social-ops/plan', 'C'],
    ['/social-ops/quality', 'C'],
    ['/social-ops/research', 'C'],
    ['/social-ops/review', 'C'],
    ['/social-ops/rewrite', 'C'],
    ['/social-ops/scripts', 'C'],
    ['/social-ops/team', 'C'],
    ['/social-ops/topics', 'C'],
    ['/social-ops/trending', 'C'],
    ['/social-ops/workshop', 'C'],
    ['/social-studio/*', 'C'],
    ['/social-studio/login', 'C'],
    ['/social/*', 'C'],
    ['/social/approval/:token', 'C'],
    ['/social/login', 'C'],
    ['/admin/agent-audit', 'D'],
    ['/admin/agent-loop-control', 'D'],
    ['/admin/agent-metrics', 'D'],
    ['/admin/agent-trace/:turnId', 'D'],
    ['/admin/agent_audit', 'D'],
    ['/admin/agent_loop_control', 'D'],
    ['/admin/agent_metrics', 'D'],
    ['/admin/agent_trace/:turnId', 'D'],
    ['/admin/auditor', 'D'],
    ['/admin/defensive-geo-settlement-review', 'D'],
    ['/admin/partner-applications', 'D'],
    ['/admin/partner-review', 'D'],
    ['/admin/roles', 'D'],
    ['/advisors', 'D'],
    ['/advisors/chat/:advisorId', 'D'],
    ['/advisors/manage', 'D'],
    ['/agent', 'D'],
    ['/agent/leads', 'D'],
    ['/agent/preview', 'D'],
    ['/agent/trial-pass-review', 'D'],
    ['/articles/progress', 'D'],
    ['/c', 'D'],
    ['/c/*', 'D'],
    ['/employees', 'D'],
    ['/employees/meeting', 'D'],
    ['/employees/meeting-history', 'D'],
    ['/employees/settings', 'D'],
    ['/employees/tasks', 'D'],
    ['/geo-research', 'D'],
    ['/imitated-articles/:articleId', 'D'],
    ['/insights', 'D'],
    ['/knowledge', 'D'],
    ['/m3', 'D'],
    ['/m3/*', 'D'],
    ['/m3/help', 'D'],
    ['/placement', 'D'],
    ['/references', 'D'],
    ['/workspace', 'D'],
];
export const RETIRED_ROUTE_COUNT = 105;
