"""包F 判据底座 —— 真 PG16 一次性库 + 现役监测最小 schema。

沿用窗A/B/C/D 的安全栓:库名必须**同时**含 ``defgeo`` 与 ``test``。
2026-08-15 实测过库名不含 ``test`` 会让安全栓整个失效、双臂 0 junit 假绿。

🔴 与窗D(W4)底座的差别:本包要打**接线**
------------------------------------------
W4 的判据全打在结构约束上(唯一约束 / 触发器 / CHECK),所以它建的是
「空库 + 只装 046」。包F ① 接的是**现役执行链**,所以判据必须能真的跑
``claim_monitoring_run_cell`` → ``finish_monitoring_cell_error`` 这条链 ——
于是本底座额外建 ``monitoring_run_cells`` / ``monitoring_tasks`` /
``monitoring_results`` / ``monitoring_cell_retry_requests`` 的
**最小真 schema**(列名/类型/CHECK 逐值取自 ``db/monitoring_db.py`` 里
那份现役约束清单,不是自己编的近似形状)。

本仓记过两条,这里都躲开:
* 「测试 schema 类型不同构照样全绿」—— 所以列类型逐值对照现役;
* 「夹具用的键是生产从来不会发的键」—— 所以夹具走的是**真函数**
  (``claim_monitoring_run_cell`` 等),不是自己拼 INSERT。

🔴 迁移**不许跳过**
------------------
跑不起来 = 判据没有被测对象。宁可当场炸,也不 skip ——
skip 掉的那条判据在报告里和"通过了"长得一模一样。
"""

from __future__ import annotations

import io
import os
from pathlib import Path

import psycopg2
import psycopg2.extras
import pytest

ROOT = Path(__file__).resolve().parents[2]

DEFAULT_THROWAWAY_URL = (
    "postgresql://geo_admin:testpw@localhost:55475/geo_defgeo_pkgf_test"
)

_REQUIRED_DB_TOKENS = ("defgeo", "test")

#: 🔴 **本包依赖的**迁移。046 建 attempt 账本那五张表。
PACKAGE_MIGRATIONS = (
    "db/migration_046_defgeo_monitoring_lineage_2026_08_22.sql",
)

LEDGER_TABLE = "defgeo_monitoring_attempts"

#: 现役监测四张表的**最小真 schema**。
#:
#: 🔴🔴 [工单 V3-C · C-5 · Codex 三审 P2-3] 措辞先说死:这是生产 DDL 的
#:    **列子集**,不是"精确生产 DDL"。它保证的只有两件事 ——
#:      · 建出来的每一列,类型与生产**同构**;
#:      · 建出来的列集合里没有生产不存在的列(2026-08-26 那次 billing_user_id
#:        就是凭空多造一列,导致真链判据全绿而生产落编造租户)。
#:    它**不保证**列是全的。因此:任何"列是否齐全 / 生产有没有这一列"的判据
#:    都**不许**拿它当分母 —— 那种问题的分母只能是真迁移文件或生产 pg_dump
#:    (本包的 e1/e3 判据走的就是那条路)。
#:
#: 🔴 逐列对照 ``db/monitoring_db.assert_monitoring_cell_retry_ready`` 里那份
#:    现役约束清单(该函数把生产 CHECK 逐字写成了字符串,是可引用的真相)。
#:    这里只建判据用得到的列,但**用到的每一列类型都与生产同构** ——
#:    类型不同构会让"判据全绿"与"根本没测到"长得一样(本仓记过)。
_LIVE_SCHEMA = """
CREATE TABLE IF NOT EXISTS monitoring_tasks (
    id            SERIAL PRIMARY KEY,
    brand_id      INTEGER NOT NULL,
    total_tests   INTEGER NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 🔴 [R2 F-1] 本表**逐列取生产 pg_dump**
--    (``tests/article_self_report_2026_08_19/prod_schema_2026-08-19.sql``
--     里的 ``CREATE TABLE public.monitoring_results``,那是仓内最新的
--     整库快照)。
--
--    R1 这里是一份**手写精简版**:只有判据当时想得到的那十几列。
--    后果是真链判据根本跑不到 —— ``save_monitoring_result`` 的 INSERT
--    有 41 列,少一列就 ``UndefinedColumn``。于是"成功路径"这条线在 R1
--    里既没有判据、也**不可能**有判据,只能绕开它去测错误路径
--    (Review F-1 抓到的就是这个)。
--
--    手写列表的通病:漏掉的那一列不会让任何判据变红,只会让判据够不到
--    被测代码。所以这里不再手写,直接抄生产。
--
--    🔴 两处**有意**的不同,都不影响本包判据,写在这里免得被当成同构:
--      · ``id`` 用 SERIAL(dump 把序列拆成独立语句了);
--      · 省掉指向 ``confirmed_keywords`` / ``brands`` 的两条外键 ——
--        那两张表不在本夹具里。指向 ``monitoring_tasks`` 的那条保留,
--        ``uq_monitoring_results_id_task`` 也保留(``monitoring_run_cells``
--        的复合外键指着它)。
--    ✅ 三条 identity CHECK **一字不改**地抄过来:pending_identity 那一臂
--       的判据正是靠 ``chk_monitoring_results_identity_markers`` 才有牙
--       (状态与 response_status/mention_type 必须成对,写歪了库层就拦)。
CREATE TABLE IF NOT EXISTS monitoring_results (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id integer,
    keyword_id integer,
    confirmed_keyword_id integer,
    keyword text NOT NULL,
    platform text NOT NULL,
    round_number integer DEFAULT 1,
    is_detected smallint DEFAULT 0,
    mention_type text DEFAULT 'none'::text,
    response_snippet text,
    full_response text,
    tested_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    response_char_count integer DEFAULT 0,
    search_citations text,
    competitors_mentioned jsonb DEFAULT '[]'::jsonb,
    sent_question_snapshot text,
    keyword_source character varying(32) DEFAULT 'legacy_unknown'::character varying,
    keyword_type character varying(32) DEFAULT 'legacy_unknown'::character varying,
    question_family character varying(64) DEFAULT 'legacy_unknown'::character varying,
    question_family_version character varying(80) DEFAULT 'legacy_unknown'::character varying,
    keyword_source_id bigint,
    keyword_resolver_status character varying(32) DEFAULT 'legacy_unknown'::character varying,
    provider character varying(64) DEFAULT 'legacy_unknown'::character varying,
    model character varying(128) DEFAULT 'legacy_unknown'::character varying,
    model_revision character varying(128) DEFAULT 'legacy_unknown'::character varying,
    model_revision_unknown_reason character varying(64),
    surface character varying(64) DEFAULT 'legacy_unknown'::character varying,
    search_mode character varying(64) DEFAULT 'legacy_unknown'::character varying,
    response_status character varying(32) DEFAULT 'legacy_unknown'::character varying,
    target_brand_snapshot text,
    target_entity_snapshot text,
    target_outcome character varying(40) DEFAULT 'legacy_unknown'::character varying,
    outcome_resolver_version character varying(80) DEFAULT 'legacy_unknown'::character varying,
    outcome_resolver_confidence numeric(5,4),
    lineage_version character varying(80) DEFAULT 'legacy_unknown'::character varying,
    lineage_status character varying(32) DEFAULT 'legacy_unknown'::character varying,
    lineage_error_reason text,
    provider_request_id text,
    sent_at timestamp with time zone,
    identity_review_state character varying(24) DEFAULT 'not_required'::character varying NOT NULL,
    identity_brand_id integer,
    identity_candidates jsonb DEFAULT '[]'::jsonb NOT NULL,
    identity_evidence_snippet text,
    identity_evidence_hash character(64),
    identity_decision_version bigint DEFAULT 0 NOT NULL,
    identity_resolved_at timestamp with time zone,
    identity_resolved_by bigint,
    CONSTRAINT uq_monitoring_results_id_task UNIQUE (id, task_id),
    CONSTRAINT chk_monitoring_results_identity_candidates CHECK ((jsonb_typeof(identity_candidates) = 'array'::text)),
    CONSTRAINT chk_monitoring_results_identity_markers CHECK ((((identity_review_state)::text = 'pending'::text) = (((response_status)::text = 'brand_identity_unresolved'::text) OR (mention_type = 'pending_identity'::text)))),
    CONSTRAINT chk_monitoring_results_identity_pending CHECK ((((identity_review_state)::text <> 'pending'::text) OR (((response_status)::text = 'brand_identity_unresolved'::text) AND (mention_type = 'pending_identity'::text) AND (identity_brand_id IS NOT NULL) AND (identity_evidence_hash IS NOT NULL) AND (identity_decision_version = 0)))),
    CONSTRAINT chk_monitoring_results_identity_review_state CHECK (((identity_review_state)::text = ANY ((ARRAY['not_required'::character varying, 'pending'::character varying, 'confirmed'::character varying, 'rejected'::character varying])::text[])))
);

-- [R2] 逐列取生产 dump。R1 没建它,于是 ``save_monitoring_result`` 里那段
-- SAVEPOINT 保护的计价写入**每次都落进 except 分支** —— 也就是说包F ⑥.2
-- 声称的"记账错位随换代自然闭合"当时只有一条 AST 锁在守,真链上那行
-- INSERT 从来没成功执行过一次。判据 ``test_cost_row_records_the_called_model``
-- 现在真的驱动它。
CREATE TABLE IF NOT EXISTS monitoring_token_usage (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id integer,
    platform text NOT NULL,
    input_tokens integer DEFAULT 0,
    output_tokens integer DEFAULT 0,
    estimated_cost real DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

-- [R2 F-3b] 退款释放那条路径的**证明 join** 要用到这两张表。
--
-- 🔴 这是本文件里唯一两张**有意做窄**的表:只建 join 真正读到的四列
--    (``point_freezes.id/task_ref`` · ``organization_charge_links.id/
--     physical_backend/physical_freeze_id/status``),列类型逐值取生产 dump。
--    它们是**资金**表,本包一个字都不改也不判 —— 在这里只是让
--    ``revoke_monitoring_task_coverage_for_organization_refund`` 的前置
--    证明能通过,好让判据够得到它后面那段真正被测的收割逻辑。
--    写清楚"窄在哪儿",免得下一个人把它当成同构的资金夹具来用。
CREATE TABLE IF NOT EXISTS point_freezes (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_ref text
);

CREATE TABLE IF NOT EXISTS organization_charge_links (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status              text NOT NULL DEFAULT 'reserved',
    physical_backend    text NOT NULL,
    physical_freeze_id  text
);

-- ══════════════════════════════════════════════════════════════════════
-- [R3] 接线点④⑤ + 重试臂 + 租约恢复的真链判据要用到的现役表
-- ══════════════════════════════════════════════════════════════════════
--
-- 🔴 R2 之前这四个 chokepoint **只有 AST 结构锁**:判据直接调桥函数
--    (`record_skip_for_plan(cur, row)` / `close_for_human_resolution(...)`),
--    那是在自证桥,不证接线。Review 亲毒(改绑 no-op、调用行保留)
--    ⇒ pkgF 90 条全绿存活。
--    要真链驱动 `create_monitoring_run_cells` / `decide_monitoring_identity_review`
--    / `reserve_monitoring_cell_retry` / `_recover_expired_monitoring_cells`,
--    就得把它们真正读写的表建齐 —— 建不齐 = 判据够不到被测代码(R2 同款教训)。
--
-- 下列表**逐列取生产 pg_dump**,CHECK 一字不改(identity 那几条是承重的)。

CREATE TABLE IF NOT EXISTS extra_keywords (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quote_id integer,
    client_id text NOT NULL,
    keyword text NOT NULL,
    target_brand text NOT NULL,
    difficulty text DEFAULT '中等'::text,
    target_rate integer DEFAULT 60,
    platforms text DEFAULT 'dashscope,deepseek,doubao,kimi,yuanbao'::text,
    note text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status text DEFAULT 'active'::text,
    brand_id integer,
    monitoring_query text,
    archive_reason text,
    archived_at timestamp without time zone,
    is_monitored boolean DEFAULT false NOT NULL,
    monitoring_enabled_at timestamp without time zone,
    monitoring_enabled_by integer
);

-- 🔴 **有意做窄**(同 client_profiles / 资金两表):生产 brands 有 35 列,
--    这里只建 `decide_monitoring_identity_review` 真正读写的那几列
--    (id / name / company_name / brand_display_names / owner_user_id /
--     is_deleted + 时间戳)。本包不判品牌域任何东西 —— 建它只是让判据
--    够得到 ⑤ 后面那段接线。窄在哪儿写在这里,免得下一个人把它当成
--    同构的品牌夹具来用。
CREATE TABLE IF NOT EXISTS brands (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    company_name text,
    brand_display_names text,
    status text DEFAULT 'active'::text,
    is_deleted boolean DEFAULT false,
    deleted_at timestamp without time zone,
    owner_user_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS roles (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    display_name text NOT NULL,
    description text,
    is_system integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS user_clients (
    user_id integer NOT NULL,
    brand_id integer NOT NULL,
    assigned_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS brand_aliases (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name text NOT NULL,
    alias text NOT NULL,
    brand_id integer,
    source text DEFAULT 'manual'::text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT brand_aliases_source_check CHECK ((source = ANY (ARRAY['manual'::text, 'auto_discovered'::text, 'llm_suggested'::text])))
);

CREATE TABLE IF NOT EXISTS monitoring_identity_decision_events (
    event_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_id integer,
    brand_id integer NOT NULL,
    action character varying(16) NOT NULL,
    selected_name text NOT NULL,
    normalized_name text NOT NULL,
    evidence_hash character(64) NOT NULL,
    result_version_before bigint NOT NULL,
    result_version_after bigint NOT NULL,
    actor_user_id bigint NOT NULL,
    request_id uuid NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    decided_at timestamp with time zone DEFAULT now() NOT NULL,
    source_kind text DEFAULT 'monitoring'::text NOT NULL,
    source_result_id bigint,
    tenant_id bigint,
    ip text,
    reason text,
    CONSTRAINT chk_monitoring_identity_event_action CHECK (((action)::text = ANY ((ARRAY['yes'::character varying, 'no'::character varying, 'custom'::character varying])::text[]))),
    CONSTRAINT chk_monitoring_identity_event_after CHECK ((result_version_after > result_version_before)),
    CONSTRAINT chk_monitoring_identity_event_before CHECK ((result_version_before >= 0)),
    CONSTRAINT chk_monitoring_identity_event_metadata CHECK ((jsonb_typeof(metadata) = 'object'::text)),
    CONSTRAINT chk_monitoring_identity_event_source CHECK ((((source_kind = 'monitoring'::text) AND (result_id IS NOT NULL)) OR ((source_kind = 'diagnosis'::text) AND (source_result_id IS NOT NULL)))),
    CONSTRAINT chk_monitoring_identity_event_source_kind CHECK ((source_kind = ANY (ARRAY['monitoring'::text, 'diagnosis'::text])))
);

CREATE TABLE IF NOT EXISTS monitoring_identity_name_decisions (
    brand_id integer NOT NULL,
    normalized_name text NOT NULL,
    display_name text NOT NULL,
    decision character varying(16) NOT NULL,
    decision_version bigint DEFAULT 1 NOT NULL,
    evidence_hash character(64) NOT NULL,
    decided_by bigint NOT NULL,
    request_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (brand_id, normalized_name),
    CONSTRAINT chk_monitoring_identity_name_decision CHECK (((decision)::text = ANY ((ARRAY['positive'::character varying, 'negative'::character varying])::text[]))),
    CONSTRAINT chk_monitoring_identity_name_version CHECK ((decision_version > 0))
);

-- 🔴 **有意做窄**(同 R2 的资金两表):`decide_monitoring_identity_review` 只
--    `UPDATE client_profiles SET brand_display_names, updated_at WHERE brand_id AND is_deleted`。
--    生产这张表 60+ 列、跟本包一个字关系都没有。窄在哪儿写在这里,
--    免得下一个人把它当同构的档案夹具用。
CREATE TABLE IF NOT EXISTS client_profiles (
    id text PRIMARY KEY,
    name text NOT NULL,
    brand_id integer,
    brand_display_names text,
    is_deleted integer DEFAULT 0,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS monitoring_run_cells (
    id                    BIGSERIAL PRIMARY KEY,
    task_id               INTEGER NOT NULL,
    brand_id              INTEGER NOT NULL,
    keyword_id            INTEGER NOT NULL,
    keyword_source        VARCHAR(16) NOT NULL,
    quote_id              INTEGER,
    keyword_snapshot      TEXT,
    question_snapshot     TEXT,
    target_brand_snapshot TEXT,
    platform              VARCHAR(32) NOT NULL,
    is_planned            BOOLEAN NOT NULL DEFAULT TRUE,
    state                 VARCHAR(40) NOT NULL,
    plan_hash             CHARACTER(64),
    fulfillment_state     VARCHAR(24) DEFAULT 'covered',
    fulfillment_credential UUID,
    settlement_reference  VARCHAR(160),
    entitlement_snapshot  JSONB,
    order_snapshot        JSONB,
    attempt_count         INTEGER NOT NULL DEFAULT 0,
    retry_count           INTEGER NOT NULL DEFAULT 0,
    result_id             INTEGER,
    -- 🔴 [工单 E3-1 · 2026-08-26] 这里原本是 `billing_user_id INTEGER` ——
    --    生产 `monitoring_run_cells` **没有这一列**(生产 pg_dump 32 列逐列
    --    核对,零命中;那一列属于 monitoring_keyword_settlements)。
    --    夹具凭空多造一列的后果不是"多测了一点":
    --      · 真链判据里桥拿到 4242、生产里桥拿到 0(键不存在)——
    --        同一段代码两边行为不同,判据全绿而生产写着编造的租户;
    --      · 更贵的一层:本包
    --        `test_open_for_claim_only_reads_keys_the_live_cell_row_really_has`
    --        就是**专门为这个 bug 写的锁**,而它的分母正是这份 _LIVE_SCHEMA ——
    --        被污染的分母让那条锁恒绿。夹具同时是锁的分母 =
    --        本仓「夹具供了生产不会供的东西」的第三形态。
    --    现在这一列是迁移 054 真加的 tenant_owner_user_id(可空 + 禁 0)。
    tenant_owner_user_id  INTEGER,
    claim_token           UUID,
    claim_until           TIMESTAMPTZ,
    provider_dispatched_at TIMESTAMPTZ,
    provider_request_id   TEXT,
    error_code            VARCHAR(80),
    error_message         TEXT,
    started_at            TIMESTAMPTZ,
    completed_at          TIMESTAMPTZ,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- 生产那条 state CHECK 逐值(见 monitoring_db 的现役约束清单)
    CONSTRAINT chk_cell_state CHECK (state IN
        ('queued','running','succeeded','failed','pending_identity',
         'unavailable','pending_provider_confirmation')),
    CONSTRAINT uq_cell_plan UNIQUE (task_id, keyword_source, keyword_id, platform),
    -- 迁移 054 逐字:NULL(未知)放行,0(编造)禁止。
    CONSTRAINT chk_monitoring_run_cells_tenant_owner_positive
        CHECK (tenant_owner_user_id IS NULL OR tenant_owner_user_id > 0)
);

CREATE TABLE IF NOT EXISTS monitoring_cell_retry_requests (
    request_id        UUID PRIMARY KEY,
    cell_id           BIGINT NOT NULL,
    task_id           INTEGER NOT NULL,
    brand_id          INTEGER NOT NULL,
    plan_hash         CHARACTER(64),
    params_hash       TEXT,
    status            VARCHAR(16) NOT NULL,
    claim_token       UUID,
    response_snapshot JSONB,
    completed_at      TIMESTAMPTZ
);
"""


def _url() -> str:
    url = os.getenv("DEFGEO_PKGF_TEST_DB_URL") or DEFAULT_THROWAWAY_URL
    dbname = url.rsplit("/", 1)[-1].lower()
    missing = [t for t in _REQUIRED_DB_TOKENS if t not in dbname]
    if missing:
        raise RuntimeError(
            f"判据库名 {dbname!r} 缺 {missing} —— 安全栓要求库名同时含 "
            "'defgeo' 与 'test'。2026-08-15 实测:库名不含 test 时安全栓整个失效,"
            "双臂 0 junit 也会显示成绿。"
        )
    return url


def _read_sql(rel: str) -> str:
    with io.open(ROOT / rel, "r", encoding="utf-8", newline="") as fh:
        return fh.read()


def _assert_fixture_actually_ran(cur) -> None:
    """活性自证:五张 defgeo 表 + 五张现役表都必须真的在。

    没有这一条,任何"在空库上跑的判据"都会全绿 —— 因为它们要打的对象
    压根不存在,而 ``CREATE TABLE IF NOT EXISTS`` 不会告诉你它没跑。
    """
    required = (LEDGER_TABLE, "monitoring_run_cells", "monitoring_tasks",
                "monitoring_results", "monitoring_cell_retry_requests",
                "monitoring_token_usage", "point_freezes",
                "organization_charge_links",
                # [R3] ④⑤/重试臂/租约恢复 真链判据要用到的现役表
                "extra_keywords", "brands", "roles", "user_roles",
                "user_clients", "brand_aliases", "client_profiles",
                "monitoring_identity_decision_events",
                "monitoring_identity_name_decisions")
    cur.execute(
        "SELECT tablename FROM pg_tables WHERE schemaname='public' "
        "AND tablename = ANY(%s)", (list(required),))
    got = {r["tablename"] for r in cur.fetchall()}
    missing = sorted(set(required) - got)
    if missing:
        raise RuntimeError(
            f"底座装完却查不到表 {missing} —— 判据没有被测对象。"
            "这一条炸了比后面一片绿有用。")
    # 承重约束的活性自证:partial unique 在不在(①的崩溃恢复全靠它)
    cur.execute(
        "SELECT indexname FROM pg_indexes WHERE schemaname='public' "
        " AND indexname='uq_defgeo_attempt_single_inflight'")
    if cur.fetchone() is None:
        raise RuntimeError(
            "uq_defgeo_attempt_single_inflight 不在 —— "
            "「同格至多一个在飞 attempt」这条承重约束没装上,"
            "所有关于崩溃恢复的判据都会假绿")


@pytest.fixture(scope="session")
def pkgf_db_url() -> str:
    return _url()


@pytest.fixture(scope="session")
def pkgf_db(pkgf_db_url):
    conn = psycopg2.connect(pkgf_db_url,
                            cursor_factory=psycopg2.extras.RealDictCursor)
    conn.autocommit = True
    with conn.cursor() as cur:
        # 冷库:上一轮变异留下的残留行会污染后续判据(本仓记过)。
        cur.execute("DROP SCHEMA IF EXISTS public CASCADE")
        cur.execute("CREATE SCHEMA public")
        cur.execute(_LIVE_SCHEMA)
        for rel in PACKAGE_MIGRATIONS:
            cur.execute(_read_sql(rel))
        _assert_fixture_actually_ran(cur)
    yield conn
    conn.close()


@pytest.fixture
def cur(pkgf_db, pkgf_db_url):
    """每条判据一个干净事务面。

    🔴 每次 yield 前清空 attempt 账本与 cell:计数式判据会被上一条判据
       留下的行写过期(本仓记过:计数式判据会被正常业务写过期,集合式不会;
       这里两种都有,所以先把分母清干净)。

    🔴🔴 **必须 autocommit=False** —— 这一条是本包最贵的一个坑,几乎让
       整片接线判据假绿:
       PostgreSQL 里 ``SAVEPOINT`` **只能在事务块内使用**。autocommit 模式下
       它报 ``SAVEPOINT can only be used in transaction blocks``,于是
       ``run_ledger_bridge.guarded`` 的第一步就失败、返回 None ——
       连 ``ledger_is_available`` 都会返 False,**每一个**桥函数变成空转。
       也就是说:判据看起来在跑真链,实际上账本一行都没写。
       (本仓记过同形的:「psql 无 BEGIN 时只读护栏静默不存在」——
        护栏语句报错被跳过,而判定看不见那个错。)

       生产是 autocommit=False(``monitoring_db`` 处处显式 ``conn.commit()``),
       所以这里必须同构。判据
       ``test_savepoint_guard_is_actually_active_in_this_fixture`` 亲自自证。
    """
    import psycopg2 as _pg
    import psycopg2.extras as _ex

    ddl = pkgf_db.cursor()
    ddl.execute(f"TRUNCATE {LEDGER_TABLE}")
    ddl.execute("TRUNCATE monitoring_run_cells, monitoring_cell_retry_requests")
    ddl.execute("TRUNCATE monitoring_results")
    ddl.execute("TRUNCATE monitoring_token_usage")
    ddl.execute("TRUNCATE point_freezes, organization_charge_links RESTART IDENTITY")
    ddl.execute("TRUNCATE extra_keywords, brand_aliases, client_profiles, monitoring_identity_decision_events, monitoring_identity_name_decisions RESTART IDENTITY")
    # 🔴 CASCADE:``db.connection.init_db`` 在本库里另建了一批表,其中
    #    ``diagnosis_records`` 有指向 ``brands`` 的外键 —— 不 CASCADE 直接
    #    ``cannot truncate a table referenced in a foreign key constraint``。
    #    被顺带清掉的都是本夹具用不到的 init_db 残留表。
    ddl.execute("TRUNCATE brands, roles, user_roles, user_clients RESTART IDENTITY CASCADE")
    ddl.execute("TRUNCATE monitoring_tasks RESTART IDENTITY CASCADE")
    ddl.close()

    conn = _pg.connect(pkgf_db_url, cursor_factory=_ex.RealDictCursor)
    conn.autocommit = False          # ← 与生产同构,SAVEPOINT 才真的存在
    c = conn.cursor()
    try:
        yield c
        conn.commit()
    finally:
        try:
            conn.rollback()
        except Exception:
            pass
        conn.close()


@pytest.fixture
def live_db(pkgf_db_url, monkeypatch, cur):
    """把 ``db.connection.get_connection`` 指向本包的一次性库。

    🔴 判据必须打**真函数**(``claim_monitoring_run_cell`` 等),不是自己拼
       INSERT —— 本仓记过「夹具用的键是生产从来不会发的键」:自己拼 INSERT
       会让整片接线判据在一个生产永不出现的形状上全绿。
    """
    import db.connection as dbconn

    def _connect():
        c = psycopg2.connect(pkgf_db_url,
                             cursor_factory=psycopg2.extras.RealDictCursor)
        # 与生产同构:**不** autocommit。见 ``cur`` fixture 里那段说明 ——
        # autocommit 下 SAVEPOINT 不存在,整片接线判据会假绿。
        c.autocommit = False
        return c

    monkeypatch.setattr(dbconn, "get_connection", _connect)
    # monitoring_db 在函数体内 ``from db.connection import get_connection``,
    # 所以模块级名字也要一起换 —— 只 patch 一处会让真函数仍连生产库。
    import db.monitoring_db as mdb
    monkeypatch.setattr(mdb, "get_connection", _connect, raising=False)
    yield _connect
