-- 自动生成：补全 PostgreSQL 中可能缺失的列
-- 使用 IF NOT EXISTS 安全执行，不会影响已有列

ALTER TABLE "advisor_conversations" ADD COLUMN IF NOT EXISTS "conversation_id" TEXT;
ALTER TABLE "advisor_conversations" ADD COLUMN IF NOT EXISTS "advisor_id" TEXT;
ALTER TABLE "advisor_conversations" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "advisor_conversations" ADD COLUMN IF NOT EXISTS "message_count" INTEGER DEFAULT 0;
ALTER TABLE "advisor_conversations" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "advisor_conversations" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "advisor_documents" ADD COLUMN IF NOT EXISTS "advisor_id" TEXT;
ALTER TABLE "advisor_documents" ADD COLUMN IF NOT EXISTS "filename" TEXT;
ALTER TABLE "advisor_documents" ADD COLUMN IF NOT EXISTS "file_type" TEXT;
ALTER TABLE "advisor_documents" ADD COLUMN IF NOT EXISTS "chunk_count" INTEGER;
ALTER TABLE "advisor_documents" ADD COLUMN IF NOT EXISTS "file_size" INTEGER;
ALTER TABLE "advisor_documents" ADD COLUMN IF NOT EXISTS "uploaded_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "advisor_messages" ADD COLUMN IF NOT EXISTS "conversation_id" TEXT;
ALTER TABLE "advisor_messages" ADD COLUMN IF NOT EXISTS "role" TEXT;
ALTER TABLE "advisor_messages" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "advisor_messages" ADD COLUMN IF NOT EXISTS "context" TEXT;
ALTER TABLE "advisor_messages" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "avatar" TEXT DEFAULT '👤';
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "base_prompt" TEXT;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "model_id" TEXT DEFAULT 'qwen3-max';
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "knowledge_path" TEXT;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "is_active" INTEGER DEFAULT 1;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "api_provider" TEXT DEFAULT 'dashscope';
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "model_name" TEXT DEFAULT 'qwen3-max';
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "enable_web_search" INTEGER DEFAULT 0;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "specialty" TEXT;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "knowledge_base_path" TEXT;
ALTER TABLE "advisors" ADD COLUMN IF NOT EXISTS "last_kb_update" TEXT;
ALTER TABLE "article_generations" ADD COLUMN IF NOT EXISTS "diagnosis_id" INTEGER;
ALTER TABLE "article_generations" ADD COLUMN IF NOT EXISTS "task_id" TEXT;
ALTER TABLE "article_generations" ADD COLUMN IF NOT EXISTS "article_type" TEXT;
ALTER TABLE "article_generations" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "article_generations" ADD COLUMN IF NOT EXISTS "word_count" INTEGER;
ALTER TABLE "article_generations" ADD COLUMN IF NOT EXISTS "file_path" TEXT;
ALTER TABLE "article_generations" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'success';
ALTER TABLE "article_generations" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "topic_id" INTEGER;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "word_count" INTEGER DEFAULT 0;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "style" TEXT;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "version" INTEGER DEFAULT 1;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "reference_article" TEXT;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "revision_note" TEXT;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'draft';
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "articles" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "user_id" INTEGER;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "username" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "action" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "module" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "entity_type" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "entity_id" INTEGER;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "summary" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "before_snapshot" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "after_snapshot" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "ip_address" TEXT;
ALTER TABLE "audit_logs" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "profile_id" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "platform" TEXT DEFAULT 'douyin';
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "sec_user_id" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "author_name" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "author_avatar" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "followers" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "following" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "total_favorited" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "aweme_count" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "signature" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "breakdown_positioning" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "breakdown_strategy" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "breakdown_hooks" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "breakdown_replication" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "breakdown_strengths" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "breakdown_improvements" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "video_ids" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "tags" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "videos_analyzed" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "knowledge_used" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "is_deleted" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_authors" ADD COLUMN IF NOT EXISTS "full_breakdown" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "profile_id" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "source_url" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "platform" TEXT DEFAULT 'douyin';
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "video_id" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "author_name" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "author_id" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "author_followers" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "stats_likes" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "stats_comments" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "stats_shares" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "stats_collects" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "stats_duration" INTEGER DEFAULT 0;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "transcript" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "analysis_positioning" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "analysis_structure" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "analysis_hook" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "analysis_copywriting" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "analysis_rewrite_formulas" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "user_visual" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "tags" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "benchmark_cards" ADD COLUMN IF NOT EXISTS "is_deleted" INTEGER DEFAULT 0;
ALTER TABLE "brand_aliases" ADD COLUMN IF NOT EXISTS "canonical_name" TEXT;
ALTER TABLE "brand_aliases" ADD COLUMN IF NOT EXISTS "alias" TEXT;
ALTER TABLE "brand_aliases" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "brand_aliases" ADD COLUMN IF NOT EXISTS "source" TEXT DEFAULT 'manual';
ALTER TABLE "brand_aliases" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "company_name" TEXT;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "industry_category" TEXT;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "contact" TEXT;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "user_id" INTEGER;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "diagnosis_count" INTEGER DEFAULT 0;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "latest_score" INTEGER;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "latest_diagnosis_id" INTEGER;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "cities" TEXT;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "brand_code" TEXT;
ALTER TABLE "brands" ADD COLUMN IF NOT EXISTS "brand_display_names" TEXT;
ALTER TABLE "client_access_tokens" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "client_access_tokens" ADD COLUMN IF NOT EXISTS "brand_name" TEXT;
ALTER TABLE "client_access_tokens" ADD COLUMN IF NOT EXISTS "token" TEXT;
ALTER TABLE "client_access_tokens" ADD COLUMN IF NOT EXISTS "is_active" SMALLINT DEFAULT 1;
ALTER TABLE "client_access_tokens" ADD COLUMN IF NOT EXISTS "expires_at" TEXT;
ALTER TABLE "client_access_tokens" ADD COLUMN IF NOT EXISTS "last_access_at" TEXT;
ALTER TABLE "client_access_tokens" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "client_id" TEXT;
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "keyword" TEXT;
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "target_brand" TEXT;
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "difficulty" TEXT DEFAULT '中等';
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "target_rate" INTEGER DEFAULT 60;
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "platforms" TEXT DEFAULT 'dashscope,deepseek,kimi,doubao';
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "note" TEXT;
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'active';
ALTER TABLE "client_keywords" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "diagnosis_id" INTEGER;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "company_intro" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "founding_year" INTEGER;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "team_size" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "service_area" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "core_selling_points" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "unique_value" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "methodology" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "case_studies" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "pricing_tiers" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "testimonials" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "credentials" TEXT;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "client_materials" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "business" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "products" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "target_users" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "pain_points" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "competitors" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "persona_positioning" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "persona_tone" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "persona_catchphrases" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "persona_background" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "persona_golden_quotes" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "target_platforms" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "successful_patterns" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "negative_feedback" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "brand_constraints" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "is_deleted" INTEGER DEFAULT 0;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "deleted_at" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "company_intro" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "core_value" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "selling_points" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "success_cases" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "testimonials" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "story_type" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "differentiation" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "content_direction" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "business_summary" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "business_misunderstandings" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "knowledge_files" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "brand_display_names" TEXT;
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "visual_style" TEXT DEFAULT '';
ALTER TABLE "client_profiles" ADD COLUMN IF NOT EXISTS "content_pillars" TEXT DEFAULT '[]';
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "keyword" TEXT;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "tier" TEXT;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "base_price" REAL;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "city_premium" REAL;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "final_price" REAL;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "competitor_count" INTEGER;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'pending';
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "selling_price" REAL DEFAULT 0;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "required_articles" INTEGER DEFAULT 1;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "recommended_platforms" TEXT;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "intent" TEXT DEFAULT 'informational';
ALTER TABLE "confirmed_keywords" ADD COLUMN IF NOT EXISTS "funnel_stage" TEXT DEFAULT 'awareness';
ALTER TABLE "departments" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "departments" ADD COLUMN IF NOT EXISTS "icon" TEXT DEFAULT '📁';
ALTER TABLE "departments" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "departments" ADD COLUMN IF NOT EXISTS "sort_order" INTEGER DEFAULT 0;
ALTER TABLE "departments" ADD COLUMN IF NOT EXISTS "is_active" SMALLINT DEFAULT 1;
ALTER TABLE "departments" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "departments" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "session_id" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "brand_name" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "industry_category" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "keywords" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "total_score" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "level" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "web_search_score" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "platform_score" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "content_quality_score" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "authority_score" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "brand_ownership_score" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "ai_visibility_score" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "ai_citation_score" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "update_frequency_score" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "ai_total_tests" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "ai_detected_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "ai_mention_rate" REAL;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "ai_engines_tested" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "douyin_video_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "douyin_brand_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "xhs_note_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "xhs_brand_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "web_result_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "web_brand_direct_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "web_authority_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "scholar_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "has_brand_presence" SMALLINT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "brand_account_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "competitor_count" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "brand_recognition_level" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "data_anomaly" SMALLINT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "anomaly_reason" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "report_md_path" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "report_json_path" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "raw_data_json" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "distilled_data" TEXT;
ALTER TABLE "diagnosis_records" ADD COLUMN IF NOT EXISTS "diagnosis_type" TEXT DEFAULT 'technical_full';
ALTER TABLE "employee_capabilities" ADD COLUMN IF NOT EXISTS "employee_id" TEXT;
ALTER TABLE "employee_capabilities" ADD COLUMN IF NOT EXISTS "capability_type" TEXT;
ALTER TABLE "employee_capabilities" ADD COLUMN IF NOT EXISTS "target_id" TEXT;
ALTER TABLE "employee_capabilities" ADD COLUMN IF NOT EXISTS "target_name" TEXT;
ALTER TABLE "employee_capabilities" ADD COLUMN IF NOT EXISTS "enabled" SMALLINT DEFAULT 1;
ALTER TABLE "employee_capabilities" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "department_id" TEXT;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "avatar" TEXT DEFAULT '🤖';
-- 2026-05-22 老板拍板:V3.2 → V4-flash 全切 · default 升级
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "model_id" TEXT DEFAULT 'deepseek-v4-flash';
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "temperature" REAL DEFAULT 0.7;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "max_tokens" INTEGER DEFAULT 4000;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "system_prompt" TEXT;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "skills" TEXT DEFAULT '[]';
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "mcp_config" TEXT DEFAULT '{}';
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "memory_type" TEXT DEFAULT 'temporary';
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "is_active" SMALLINT DEFAULT 1;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "sort_order" INTEGER DEFAULT 0;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "usage_scope" TEXT DEFAULT 'all';
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "employee_configs" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "meeting_id" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "topic" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "context" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "brand_name" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "is_internal" SMALLINT DEFAULT 0;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "participants" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "participant_ids" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "moderator_id" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "moderator_name" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "transcript" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "conclusion" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "summary" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "action_items" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "attachments" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'pending';
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "rounds" INTEGER DEFAULT 2;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "duration" REAL;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "tags" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "started_at" TEXT;
ALTER TABLE "employee_meetings" ADD COLUMN IF NOT EXISTS "completed_at" TEXT;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "employee_id" TEXT;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "employee_name" TEXT;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "task_type" TEXT DEFAULT 'single';
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "task_content" TEXT;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "context" TEXT;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "result" TEXT;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'pending';
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "skills_used" TEXT;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "execution_time" REAL;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "error_message" TEXT;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "employee_tasks" ADD COLUMN IF NOT EXISTS "completed_at" TEXT;
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "client_id" TEXT;
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "keyword" TEXT;
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "target_brand" TEXT;
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "difficulty" TEXT DEFAULT '中等';
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "target_rate" INTEGER DEFAULT 60;
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "platforms" TEXT DEFAULT 'dashscope,deepseek,kimi,doubao';
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "note" TEXT;
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'active';
ALTER TABLE "extra_keywords" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "geo_engine_stats" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "geo_engine_stats" ADD COLUMN IF NOT EXISTS "engine" TEXT;
ALTER TABLE "geo_engine_stats" ADD COLUMN IF NOT EXISTS "platform" TEXT;
ALTER TABLE "geo_engine_stats" ADD COLUMN IF NOT EXISTS "citation_count" INTEGER DEFAULT 0;
ALTER TABLE "geo_engine_stats" ADD COLUMN IF NOT EXISTS "total_queries" INTEGER DEFAULT 0;
ALTER TABLE "geo_engine_stats" ADD COLUMN IF NOT EXISTS "citation_rate" REAL DEFAULT 0;
ALTER TABLE "geo_engine_stats" ADD COLUMN IF NOT EXISTS "avg_position" REAL DEFAULT 0;
ALTER TABLE "geo_engine_stats" ADD COLUMN IF NOT EXISTS "sample_queries" INTEGER DEFAULT 0;
ALTER TABLE "geo_engine_stats" ADD COLUMN IF NOT EXISTS "last_updated" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "geo_engine_weights" ADD COLUMN IF NOT EXISTS "engine" TEXT;
ALTER TABLE "geo_engine_weights" ADD COLUMN IF NOT EXISTS "weight" REAL DEFAULT 0.25;
ALTER TABLE "geo_engine_weights" ADD COLUMN IF NOT EXISTS "mau_millions" REAL;
ALTER TABLE "geo_engine_weights" ADD COLUMN IF NOT EXISTS "source" TEXT;
ALTER TABLE "geo_engine_weights" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "geo_research_batches" ADD COLUMN IF NOT EXISTS "batch_id" TEXT;
ALTER TABLE "geo_research_batches" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "geo_research_batches" ADD COLUMN IF NOT EXISTS "engine" TEXT;
ALTER TABLE "geo_research_batches" ADD COLUMN IF NOT EXISTS "query_count" INTEGER DEFAULT 0;
ALTER TABLE "geo_research_batches" ADD COLUMN IF NOT EXISTS "researcher" TEXT;
ALTER TABLE "geo_research_batches" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "geo_research_batches" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'pending';
ALTER TABLE "geo_research_batches" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "geo_research_batches" ADD COLUMN IF NOT EXISTS "completed_at" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "query" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "engine" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "cited_platform" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "cite_position" INTEGER DEFAULT 0;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "cite_url" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "batch_id" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "researcher" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "cite_title" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "cite_excerpt" TEXT;
ALTER TABLE "geo_research_raw" ADD COLUMN IF NOT EXISTS "answer_text" TEXT;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "imitation_record_id" INTEGER;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "reference_id" INTEGER;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "keyword" TEXT;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "word_count" INTEGER;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'draft';
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "revision_notes" TEXT;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "imitated_articles" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "imitation_records" ADD COLUMN IF NOT EXISTS "reference_id" INTEGER;
ALTER TABLE "imitation_records" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "imitation_records" ADD COLUMN IF NOT EXISTS "generated_count" INTEGER;
ALTER TABLE "imitation_records" ADD COLUMN IF NOT EXISTS "success_count" INTEGER DEFAULT 0;
ALTER TABLE "imitation_records" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "task_id" INTEGER;
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "client_id" TEXT;
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "keyword" TEXT;
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "platforms_analyzed" TEXT DEFAULT '[]';
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "brands_found" TEXT DEFAULT '[]';
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "sources_cited" TEXT DEFAULT '[]';
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "response_patterns" TEXT DEFAULT '{}';
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "client_position" TEXT DEFAULT '{}';
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "optimization_hints" TEXT DEFAULT '[]';
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "llm_model" TEXT DEFAULT 'qwen3-max';
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "llm_tokens" INTEGER DEFAULT 0;
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "algorithm_version" TEXT DEFAULT 'v4.2';
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "quality_flag" TEXT DEFAULT 'auto';
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "feedback_note" TEXT;
ALTER TABLE "keyword_insights" ADD COLUMN IF NOT EXISTS "distilled_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "keyword_interaction_logs" ADD COLUMN IF NOT EXISTS "session_id" INTEGER;
ALTER TABLE "keyword_interaction_logs" ADD COLUMN IF NOT EXISTS "phase" TEXT;
ALTER TABLE "keyword_interaction_logs" ADD COLUMN IF NOT EXISTS "event_type" TEXT;
ALTER TABLE "keyword_interaction_logs" ADD COLUMN IF NOT EXISTS "keyword_id" INTEGER;
ALTER TABLE "keyword_interaction_logs" ADD COLUMN IF NOT EXISTS "keyword_text" TEXT;
ALTER TABLE "keyword_interaction_logs" ADD COLUMN IF NOT EXISTS "event_data" TEXT;
ALTER TABLE "keyword_interaction_logs" ADD COLUMN IF NOT EXISTS "client_ip" TEXT;
ALTER TABLE "keyword_interaction_logs" ADD COLUMN IF NOT EXISTS "user_agent" TEXT;
ALTER TABLE "keyword_interaction_logs" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "brand_name" TEXT;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "keyword" TEXT;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "difficulty_score" REAL;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "value_score" REAL;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "competitor_count" INTEGER;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "cost_per_article" REAL;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "intent" TEXT;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "funnel_stage" TEXT;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "search_probability" REAL;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "search_volume" INTEGER;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "sem_price" REAL;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "bidword_company_count" INTEGER;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "content_count" INTEGER;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "source_authority_json" TEXT;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "recommended_platforms_json" TEXT;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "data_source" TEXT;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "markup_ratio" REAL;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "entry_price" REAL;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "entry_articles" INTEGER;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "standard_price" REAL;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "standard_articles" INTEGER;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "flagship_price" REAL;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "flagship_articles" INTEGER;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "cached_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "keyword_price_cache" ADD COLUMN IF NOT EXISTS "expires_at" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "token" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "created_by" INTEGER;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "keywords_snapshot" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'selecting';
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "expires_at" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "selected_keyword_ids" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "custom_keywords" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "keywords_submitted_at" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "pricing_data" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "selected_tier" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "final_keyword_ids" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "confirmed_at" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "confirmed_total_price" REAL;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "pending_keywords" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "total_time_seconds" INTEGER;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "visit_count" INTEGER DEFAULT 0;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "hesitation_summary" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "final_price" REAL;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "discount_info" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "gift_keywords" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "gift_articles" INTEGER DEFAULT 0;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "sales_notes" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "sales_confirmed_at" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "payment_received_at" TEXT;
ALTER TABLE "keyword_selection_sessions" ADD COLUMN IF NOT EXISTS "payment_overdue_notified_days" TEXT DEFAULT '[]';
ALTER TABLE "keyword_trend_stats" ADD COLUMN IF NOT EXISTS "keyword_id" INTEGER;
ALTER TABLE "keyword_trend_stats" ADD COLUMN IF NOT EXISTS "keyword_source" TEXT DEFAULT 'confirmed';
ALTER TABLE "keyword_trend_stats" ADD COLUMN IF NOT EXISTS "period_type" TEXT;
ALTER TABLE "keyword_trend_stats" ADD COLUMN IF NOT EXISTS "period_date" TEXT;
ALTER TABLE "keyword_trend_stats" ADD COLUMN IF NOT EXISTS "test_count" INTEGER DEFAULT 0;
ALTER TABLE "keyword_trend_stats" ADD COLUMN IF NOT EXISTS "detected_count" INTEGER DEFAULT 0;
ALTER TABLE "keyword_trend_stats" ADD COLUMN IF NOT EXISTS "detection_rate" REAL DEFAULT 0;
ALTER TABLE "keyword_trend_stats" ADD COLUMN IF NOT EXISTS "rate_change" REAL DEFAULT 0;
ALTER TABLE "keyword_trend_stats" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "task_id" TEXT;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "file_name" TEXT;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "file_type" TEXT;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'pending';
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "total_rows" INTEGER DEFAULT 0;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "processed_rows" INTEGER DEFAULT 0;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "chunk_count" INTEGER DEFAULT 0;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "new_outlets_count" INTEGER DEFAULT 0;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "updated_outlets_count" INTEGER DEFAULT 0;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "discoveries" TEXT;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "insights" TEXT;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "previous_log_id" INTEGER;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "delta_summary" TEXT;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "completed_at" TEXT;
ALTER TABLE "media_analysis_log" ADD COLUMN IF NOT EXISTS "error_message" TEXT;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "media_type" TEXT DEFAULT 'traditional';
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "platform" TEXT;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "sivp_price" REAL;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "min_price" REAL;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "max_price" REAL;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "ai_engines_covered" TEXT DEFAULT '[]';
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "ai_coverage_count" INTEGER DEFAULT 0;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "geo_confirmed" INTEGER DEFAULT 0;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "geo_notes" TEXT;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "citation_count" INTEGER DEFAULT 0;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "region" TEXT;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "baidu_news_source" INTEGER DEFAULT 0;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "suitable_industries" TEXT DEFAULT '[]';
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "data_source" TEXT;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "source_url" TEXT;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "media_outlets" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "media_publications" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "media_publications" ADD COLUMN IF NOT EXISTS "article_id" INTEGER;
ALTER TABLE "media_publications" ADD COLUMN IF NOT EXISTS "platform_name" TEXT;
ALTER TABLE "media_publications" ADD COLUMN IF NOT EXISTS "platform_url" TEXT;
ALTER TABLE "media_publications" ADD COLUMN IF NOT EXISTS "article_title" TEXT;
ALTER TABLE "media_publications" ADD COLUMN IF NOT EXISTS "publish_date" TEXT;
ALTER TABLE "media_publications" ADD COLUMN IF NOT EXISTS "operator_id" TEXT;
ALTER TABLE "media_publications" ADD COLUMN IF NOT EXISTS "screenshot_path" TEXT;
ALTER TABLE "media_publications" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "meeting_presets" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "meeting_presets" ADD COLUMN IF NOT EXISTS "style" TEXT;
ALTER TABLE "meeting_presets" ADD COLUMN IF NOT EXISTS "rounds" INTEGER DEFAULT 2;
ALTER TABLE "meeting_presets" ADD COLUMN IF NOT EXISTS "co_moderator_id" TEXT;
ALTER TABLE "meeting_presets" ADD COLUMN IF NOT EXISTS "co_moderator_name" TEXT;
ALTER TABLE "meeting_presets" ADD COLUMN IF NOT EXISTS "weight_boost" REAL DEFAULT 1.5;
ALTER TABLE "meeting_presets" ADD COLUMN IF NOT EXISTS "auto_execute" SMALLINT DEFAULT 0;
ALTER TABLE "meeting_presets" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "meeting_presets" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monitoring_config" ADD COLUMN IF NOT EXISTS "client_id" TEXT;
ALTER TABLE "monitoring_config" ADD COLUMN IF NOT EXISTS "default_concurrency" INTEGER DEFAULT 10;
ALTER TABLE "monitoring_config" ADD COLUMN IF NOT EXISTS "default_platforms" TEXT DEFAULT 'dashscope,deepseek,kimi,doubao';
ALTER TABLE "monitoring_config" ADD COLUMN IF NOT EXISTS "auto_monitor_enabled" SMALLINT DEFAULT 0;
ALTER TABLE "monitoring_config" ADD COLUMN IF NOT EXISTS "auto_monitor_cron" TEXT;
ALTER TABLE "monitoring_config" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monitoring_config" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "client_id" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "report_type" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "period_start" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "period_end" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "summary_data" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "excel_path" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "pdf_path" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'draft';
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "reviewed_by" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "reviewed_at" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "sent_at" TEXT;
ALTER TABLE "monitoring_reports" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "task_id" INTEGER;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "keyword_id" INTEGER;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "confirmed_keyword_id" INTEGER;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "keyword" TEXT;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "platform" TEXT;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "round_number" INTEGER DEFAULT 1;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "is_detected" SMALLINT DEFAULT 0;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "mention_type" TEXT DEFAULT 'none';
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "response_snippet" TEXT;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "full_response" TEXT;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "tested_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "response_char_count" INTEGER DEFAULT 0;
ALTER TABLE "monitoring_results" ADD COLUMN IF NOT EXISTS "search_citations" TEXT;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "client_id" TEXT;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "task_name" TEXT;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "keyword_count" INTEGER DEFAULT 0;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "platform_count" INTEGER DEFAULT 4;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "total_tests" INTEGER DEFAULT 0;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "completed_tests" INTEGER DEFAULT 0;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "concurrency" INTEGER DEFAULT 10;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "test_rounds" INTEGER DEFAULT 3;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'pending';
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "started_at" TEXT;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "completed_at" TEXT;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "result_summary" TEXT;
ALTER TABLE "monitoring_tasks" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "monitoring_token_usage" ADD COLUMN IF NOT EXISTS "task_id" INTEGER;
ALTER TABLE "monitoring_token_usage" ADD COLUMN IF NOT EXISTS "platform" TEXT;
ALTER TABLE "monitoring_token_usage" ADD COLUMN IF NOT EXISTS "input_tokens" INTEGER DEFAULT 0;
ALTER TABLE "monitoring_token_usage" ADD COLUMN IF NOT EXISTS "output_tokens" INTEGER DEFAULT 0;
ALTER TABLE "monitoring_token_usage" ADD COLUMN IF NOT EXISTS "estimated_cost" REAL DEFAULT 0;
ALTER TABLE "monitoring_token_usage" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "client_id" INTEGER;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "type" TEXT;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "related_id" INTEGER;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "is_read" INTEGER DEFAULT 0;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "operation_logs" ADD COLUMN IF NOT EXISTS "operator_id" TEXT;
ALTER TABLE "operation_logs" ADD COLUMN IF NOT EXISTS "action" TEXT;
ALTER TABLE "operation_logs" ADD COLUMN IF NOT EXISTS "target_type" TEXT;
ALTER TABLE "operation_logs" ADD COLUMN IF NOT EXISTS "target_id" INTEGER;
ALTER TABLE "operation_logs" ADD COLUMN IF NOT EXISTS "details" TEXT;
ALTER TABLE "operation_logs" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "placement_recommendations" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "placement_recommendations" ADD COLUMN IF NOT EXISTS "topic_id" INTEGER;
ALTER TABLE "placement_recommendations" ADD COLUMN IF NOT EXISTS "article_id" INTEGER;
ALTER TABLE "placement_recommendations" ADD COLUMN IF NOT EXISTS "recommended_outlets" TEXT DEFAULT '[]';
ALTER TABLE "placement_recommendations" ADD COLUMN IF NOT EXISTS "total_estimated_cost" REAL;
ALTER TABLE "placement_recommendations" ADD COLUMN IF NOT EXISTS "strategy_tier" TEXT DEFAULT 'budget';
ALTER TABLE "placement_recommendations" ADD COLUMN IF NOT EXISTS "llm_analysis" TEXT;
ALTER TABLE "placement_recommendations" ADD COLUMN IF NOT EXISTS "llm_model" TEXT;
ALTER TABLE "placement_recommendations" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "diagnosis_id" INTEGER;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "brand_name" TEXT;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "city" TEXT;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "tier" TEXT;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "target_share" REAL;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "total_keywords" INTEGER;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "total_articles" INTEGER;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "monthly_price" REAL;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "paid_amount" REAL;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'draft';
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "confirmed_at" TEXT;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "paid_at" TEXT;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "markdown" TEXT;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "writing_status" TEXT DEFAULT 'pending';
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "distilled_data" TEXT;
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "competitor_mode" TEXT DEFAULT 'fictional';
ALTER TABLE "quotes" ADD COLUMN IF NOT EXISTS "competitor_list" TEXT DEFAULT '';
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "source_url" TEXT;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "platform" TEXT;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "intent_type" TEXT;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "analysis" TEXT;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "success_proof" TEXT;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "use_count" INTEGER DEFAULT 0;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "success_rate" REAL DEFAULT 0;
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'active';
ALTER TABLE "reference_articles" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "result_types" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "result_types" ADD COLUMN IF NOT EXISTS "icon" TEXT DEFAULT '📄';
ALTER TABLE "result_types" ADD COLUMN IF NOT EXISTS "color" TEXT DEFAULT '#6366f1';
ALTER TABLE "result_types" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "result_types" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "role_permissions" ADD COLUMN IF NOT EXISTS "role_id" INTEGER;
ALTER TABLE "role_permissions" ADD COLUMN IF NOT EXISTS "module" TEXT;
ALTER TABLE "role_permissions" ADD COLUMN IF NOT EXISTS "level" TEXT DEFAULT 'read';
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "display_name" TEXT;
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "is_system" INTEGER DEFAULT 0;
ALTER TABLE "roles" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_benchmarks" ADD COLUMN IF NOT EXISTS "project_id" INTEGER;
ALTER TABLE "social_benchmarks" ADD COLUMN IF NOT EXISTS "platform" TEXT;
ALTER TABLE "social_benchmarks" ADD COLUMN IF NOT EXISTS "account_id" TEXT;
ALTER TABLE "social_benchmarks" ADD COLUMN IF NOT EXISTS "account_name" TEXT;
ALTER TABLE "social_benchmarks" ADD COLUMN IF NOT EXISTS "follower_count" INTEGER DEFAULT 0;
ALTER TABLE "social_benchmarks" ADD COLUMN IF NOT EXISTS "is_competitor" INTEGER DEFAULT 0;
ALTER TABLE "social_benchmarks" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "social_benchmarks" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "project_id" INTEGER;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "platform" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "video_id" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "video_url" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "author_name" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "author_id" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "transcript" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "opening_type" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "content_type" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "structure_analysis" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "golden_phrases" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "stats_digg" INTEGER DEFAULT 0;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "stats_comment" INTEGER DEFAULT 0;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "stats_share" INTEGER DEFAULT 0;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "profile_id" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "advisor_id" TEXT;
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "update_source" TEXT DEFAULT 'ai_generated';
ALTER TABLE "social_materials" ADD COLUMN IF NOT EXISTS "material_type" TEXT DEFAULT 'video';
ALTER TABLE "social_personas" ADD COLUMN IF NOT EXISTS "project_id" INTEGER;
ALTER TABLE "social_personas" ADD COLUMN IF NOT EXISTS "one_liner" TEXT;
ALTER TABLE "social_personas" ADD COLUMN IF NOT EXISTS "visual_style" TEXT;
ALTER TABLE "social_personas" ADD COLUMN IF NOT EXISTS "speaking_style" TEXT;
ALTER TABLE "social_personas" ADD COLUMN IF NOT EXISTS "target_audience" TEXT;
ALTER TABLE "social_personas" ADD COLUMN IF NOT EXISTS "content_pillars" TEXT;
ALTER TABLE "social_personas" ADD COLUMN IF NOT EXISTS "persona_details" TEXT;
ALTER TABLE "social_personas" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_personas" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "name" TEXT;
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "industry" TEXT;
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "business" TEXT;
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "target_audience" TEXT;
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "product_intro" TEXT;
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "advisor_style" TEXT DEFAULT '小黄编导';
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'active';
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "social_projects" ADD COLUMN IF NOT EXISTS "profile_id" TEXT;
ALTER TABLE "social_script_versions" ADD COLUMN IF NOT EXISTS "script_id" INTEGER;
ALTER TABLE "social_script_versions" ADD COLUMN IF NOT EXISTS "version_num" INTEGER DEFAULT 1;
ALTER TABLE "social_script_versions" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "social_script_versions" ADD COLUMN IF NOT EXISTS "change_reason" TEXT;
ALTER TABLE "social_script_versions" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "project_id" INTEGER;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "topic_id" INTEGER;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "script_content" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "opening_type" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "content_type" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "word_count" INTEGER DEFAULT 0;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "source" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "source_video_url" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "original_transcript" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'draft';
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "publish_date" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "performance_data" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "updated_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "profile_id" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "advisor_id" TEXT;
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "update_source" TEXT DEFAULT 'manual';
ALTER TABLE "social_scripts" ADD COLUMN IF NOT EXISTS "is_filmed" INTEGER DEFAULT 0;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "project_id" INTEGER;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "topic_type" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "content_type" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "user_level" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "opening_type" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "source" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "source_video_id" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'pending';
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "priority" INTEGER DEFAULT 0;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "used_at" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "profile_id" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "advisor_id" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "update_source" TEXT DEFAULT 'manual';
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "title_hash" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "skipped_at" TEXT;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "view_count" INTEGER DEFAULT 0;
ALTER TABLE "social_topics" ADD COLUMN IF NOT EXISTS "last_shown_at" TEXT;
ALTER TABLE "token_usage" ADD COLUMN IF NOT EXISTS "task_id" TEXT;
ALTER TABLE "token_usage" ADD COLUMN IF NOT EXISTS "diagnosis_id" INTEGER;
ALTER TABLE "token_usage" ADD COLUMN IF NOT EXISTS "model_name" TEXT;
ALTER TABLE "token_usage" ADD COLUMN IF NOT EXISTS "input_tokens" INTEGER;
ALTER TABLE "token_usage" ADD COLUMN IF NOT EXISTS "output_tokens" INTEGER;
ALTER TABLE "token_usage" ADD COLUMN IF NOT EXISTS "total_tokens" INTEGER;
ALTER TABLE "token_usage" ADD COLUMN IF NOT EXISTS "estimated_cost" REAL;
ALTER TABLE "token_usage" ADD COLUMN IF NOT EXISTS "operation_type" TEXT;
ALTER TABLE "token_usage" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "topic_embeddings" ADD COLUMN IF NOT EXISTS "topic_id" INTEGER;
ALTER TABLE "topic_embeddings" ADD COLUMN IF NOT EXISTS "project_id" INTEGER;
ALTER TABLE "topic_embeddings" ADD COLUMN IF NOT EXISTS "embedding" TEXT;
ALTER TABLE "topic_embeddings" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "keyword_id" INTEGER;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "quote_id" INTEGER;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "original_keyword" TEXT;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "optimized_title" TEXT;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "article_style" TEXT;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "article_id" INTEGER;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT 'draft';
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "confirmed_at" TEXT;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "regenerate_count" INTEGER DEFAULT 0;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "completed_at" TEXT;
ALTER TABLE "topics" ADD COLUMN IF NOT EXISTS "reviewed_at" TEXT;
ALTER TABLE "user_clients" ADD COLUMN IF NOT EXISTS "assigned_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "username" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password_hash" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "display_name" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_active" INTEGER DEFAULT 1;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "permission_version" INTEGER DEFAULT 1;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "must_change_password" INTEGER DEFAULT 1;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "avatar_url" TEXT;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "last_login_at" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "title" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "result_type" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "brand_id" INTEGER;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "brand_name" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "meeting_id" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "assignee_id" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "assignee_name" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "content" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "attachments" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "tags" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "keywords" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "status" TEXT DEFAULT '待执行';
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "priority" INTEGER DEFAULT 2;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "due_date" TEXT;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "created_at" TEXT DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "work_results" ADD COLUMN IF NOT EXISTS "completed_at" TEXT;
