-- Durable word x platform execution plan and covered single-cell retry ledger.
-- Additive/idempotent. It never changes billing prices, balances, or feature flags.
SET LOCAL search_path = pg_catalog, public;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '120s';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_constraint
         WHERE conrelid = 'public.monitoring_tasks'::regclass
           AND conname = 'uq_monitoring_tasks_id_brand'
    ) THEN
        ALTER TABLE public.monitoring_tasks
            ADD CONSTRAINT uq_monitoring_tasks_id_brand UNIQUE (id, brand_id);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_constraint
         WHERE conrelid = 'public.quotes'::regclass
           AND conname = 'uq_quotes_id_brand'
    ) AND pg_catalog.to_regclass('public.ux_quotes_id_brand') IS NULL THEN
        -- The quote snapshot migration (earlier in the unified manifest)
        -- already creates an exact non-partial unique btree on this key.
        -- Reuse it as the FK authority instead of scanning/locking quotes to
        -- build a second equivalent unique object.
        ALTER TABLE public.quotes
            ADD CONSTRAINT uq_quotes_id_brand UNIQUE (id, brand_id);
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_constraint
         WHERE conrelid = 'public.monitoring_results'::regclass
           AND conname = 'uq_monitoring_results_id_task'
    ) THEN
        ALTER TABLE public.monitoring_results
            ADD CONSTRAINT uq_monitoring_results_id_task UNIQUE (id, task_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.monitoring_run_cells (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id INTEGER NOT NULL,
    brand_id INTEGER NOT NULL,
    keyword_id BIGINT NOT NULL,
    keyword_source VARCHAR(16) NOT NULL,
    quote_id INTEGER,
    keyword_snapshot TEXT NOT NULL,
    question_snapshot TEXT NOT NULL,
    target_brand_snapshot TEXT NOT NULL,
    platform VARCHAR(32) NOT NULL,
    is_planned BOOLEAN NOT NULL,
    state VARCHAR(40) NOT NULL DEFAULT 'queued',
    entitlement_snapshot JSONB NOT NULL,
    order_snapshot JSONB NOT NULL,
    fulfillment_credential UUID NOT NULL,
    fulfillment_state VARCHAR(24) NOT NULL DEFAULT 'reserved',
    settlement_reference VARCHAR(160),
    plan_hash CHAR(64) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    claim_token UUID,
    claim_until TIMESTAMPTZ,
    provider_dispatched_at TIMESTAMPTZ,
    provider_request_id TEXT,
    result_id INTEGER,
    error_code VARCHAR(80),
    error_message TEXT,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_monitoring_run_cells_plan
        UNIQUE (task_id, keyword_source, keyword_id, platform),
    CONSTRAINT uq_monitoring_run_cells_retry_scope
        UNIQUE (id, task_id, brand_id, plan_hash),
    CONSTRAINT fk_monitoring_run_cells_task
        FOREIGN KEY (task_id) REFERENCES public.monitoring_tasks(id) ON DELETE RESTRICT,
    CONSTRAINT fk_monitoring_run_cells_task_brand
        FOREIGN KEY (task_id, brand_id)
        REFERENCES public.monitoring_tasks(id, brand_id) ON DELETE RESTRICT,
    CONSTRAINT fk_monitoring_run_cells_brand
        FOREIGN KEY (brand_id) REFERENCES public.brands(id) ON DELETE RESTRICT,
    CONSTRAINT fk_monitoring_run_cells_quote_brand
        FOREIGN KEY (quote_id, brand_id)
        REFERENCES public.quotes(id, brand_id) ON DELETE RESTRICT,
    CONSTRAINT fk_monitoring_run_cells_result_task
        FOREIGN KEY (result_id, task_id)
        REFERENCES public.monitoring_results(id, task_id) ON DELETE RESTRICT,
    CONSTRAINT chk_monitoring_run_cells_keyword_source
        CHECK (keyword_source IN ('confirmed', 'contract', 'extra')),
    CONSTRAINT chk_monitoring_run_cells_platform
        CHECK (platform IN ('dashscope', 'deepseek', 'kimi', 'doubao')),
    CONSTRAINT chk_monitoring_run_cells_state
        CHECK (state IN (
            'queued', 'running', 'succeeded', 'failed', 'pending_identity',
            'unavailable', 'pending_provider_confirmation'
        )),
    CONSTRAINT chk_monitoring_run_cells_fulfillment_state
        CHECK (fulfillment_state IN (
            'reserved', 'covered', 'admin_covered', 'coverage_unknown', 'released'
        )),
    CONSTRAINT chk_monitoring_run_cells_counts
        CHECK (attempt_count >= 0 AND retry_count >= 0 AND retry_count <= attempt_count),
    CONSTRAINT chk_monitoring_run_cells_json
        CHECK (
            pg_catalog.jsonb_typeof(entitlement_snapshot) = 'object'
            AND pg_catalog.jsonb_typeof(order_snapshot) = 'object'
        ),
    CONSTRAINT chk_monitoring_run_cells_plan_shape
        CHECK (
            is_planned
            OR (NOT is_planned AND state = 'unavailable')
        ),
    CONSTRAINT chk_monitoring_run_cells_result_terminal
        CHECK (
            (state IN ('succeeded', 'pending_identity') AND result_id IS NOT NULL)
            OR (state NOT IN ('succeeded', 'pending_identity') AND result_id IS NULL)
        ),
    CONSTRAINT chk_monitoring_run_cells_claim
        CHECK (
            (state = 'running' AND claim_token IS NOT NULL AND claim_until IS NOT NULL)
            OR (state <> 'running' AND claim_token IS NULL AND claim_until IS NULL)
        )
);

-- @index-guard ux_monitoring_run_cells_result ON monitoring_run_cells unique
DO $idxguard$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_index i ON i.indexrelid = c.oid
                WHERE c.relname = 'ux_monitoring_run_cells_result' AND i.indrelid = to_regclass('public.monitoring_run_cells')) THEN
        NULL;  -- 已在 public.monitoring_run_cells 上 → 幂等跳过
    ELSIF EXISTS (SELECT 1 FROM pg_class c
                   WHERE c.relname = 'ux_monitoring_run_cells_result' AND c.relnamespace = 'public'::regnamespace) THEN
        RAISE EXCEPTION '[index-guard] ux_monitoring_run_cells_result 已存在但不在 public.monitoring_run_cells 上(实际宿主:%)—— 拒绝静默跳过',
            (SELECT COALESCE(t.relname, 'relkind=' || c.relkind::text) FROM pg_class c
               LEFT JOIN pg_index i ON i.indexrelid = c.oid
               LEFT JOIN pg_class t ON t.oid = i.indrelid
              WHERE c.relname = 'ux_monitoring_run_cells_result' AND c.relnamespace = 'public'::regnamespace)
            USING ERRCODE = 'duplicate_object';
    ELSE
        CREATE UNIQUE INDEX ux_monitoring_run_cells_result ON public.monitoring_run_cells (result_id) WHERE result_id IS NOT NULL;
    END IF;
END $idxguard$;
-- @index-guard idx_monitoring_run_cells_task_state ON monitoring_run_cells plain
DO $idxguard$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_index i ON i.indexrelid = c.oid
                WHERE c.relname = 'idx_monitoring_run_cells_task_state' AND i.indrelid = to_regclass('public.monitoring_run_cells')) THEN
        NULL;  -- 已在 public.monitoring_run_cells 上 → 幂等跳过
    ELSIF EXISTS (SELECT 1 FROM pg_class c
                   WHERE c.relname = 'idx_monitoring_run_cells_task_state' AND c.relnamespace = 'public'::regnamespace) THEN
        RAISE EXCEPTION '[index-guard] idx_monitoring_run_cells_task_state 已存在但不在 public.monitoring_run_cells 上(实际宿主:%)—— 拒绝静默跳过',
            (SELECT COALESCE(t.relname, 'relkind=' || c.relkind::text) FROM pg_class c
               LEFT JOIN pg_index i ON i.indexrelid = c.oid
               LEFT JOIN pg_class t ON t.oid = i.indrelid
              WHERE c.relname = 'idx_monitoring_run_cells_task_state' AND c.relnamespace = 'public'::regnamespace)
            USING ERRCODE = 'duplicate_object';
    ELSE
        CREATE INDEX idx_monitoring_run_cells_task_state ON public.monitoring_run_cells (task_id, state, id);
    END IF;
END $idxguard$;
-- @index-guard idx_monitoring_run_cells_expired_claim ON monitoring_run_cells plain
DO $idxguard$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_index i ON i.indexrelid = c.oid
                WHERE c.relname = 'idx_monitoring_run_cells_expired_claim' AND i.indrelid = to_regclass('public.monitoring_run_cells')) THEN
        NULL;  -- 已在 public.monitoring_run_cells 上 → 幂等跳过
    ELSIF EXISTS (SELECT 1 FROM pg_class c
                   WHERE c.relname = 'idx_monitoring_run_cells_expired_claim' AND c.relnamespace = 'public'::regnamespace) THEN
        RAISE EXCEPTION '[index-guard] idx_monitoring_run_cells_expired_claim 已存在但不在 public.monitoring_run_cells 上(实际宿主:%)—— 拒绝静默跳过',
            (SELECT COALESCE(t.relname, 'relkind=' || c.relkind::text) FROM pg_class c
               LEFT JOIN pg_index i ON i.indexrelid = c.oid
               LEFT JOIN pg_class t ON t.oid = i.indrelid
              WHERE c.relname = 'idx_monitoring_run_cells_expired_claim' AND c.relnamespace = 'public'::regnamespace)
            USING ERRCODE = 'duplicate_object';
    ELSE
        CREATE INDEX idx_monitoring_run_cells_expired_claim ON public.monitoring_run_cells (claim_until, id) WHERE state = 'running';
    END IF;
END $idxguard$;

CREATE TABLE IF NOT EXISTS public.monitoring_keyword_settlements (
    settlement_reference VARCHAR(160) PRIMARY KEY,
    task_id INTEGER NOT NULL,
    brand_id INTEGER NOT NULL,
    keyword_id BIGINT NOT NULL,
    keyword_source VARCHAR(24) NOT NULL,
    subscription_id INTEGER,
    billing_user_id INTEGER,
    feature_code VARCHAR(80) NOT NULL,
    claim_token TIMESTAMP,
    previous_claim_at TIMESTAMP,
    freeze_id BIGINT,
    freeze_table VARCHAR(16),
    frozen_amount BIGINT NOT NULL DEFAULT 0,
    state VARCHAR(32) NOT NULL DEFAULT 'reserved',
    charge_recorded BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_monitoring_keyword_settlement_scope
        UNIQUE (task_id, keyword_source, keyword_id),
    CONSTRAINT fk_monitoring_keyword_settlement_task_brand
        FOREIGN KEY (task_id, brand_id)
        REFERENCES public.monitoring_tasks(id, brand_id) ON DELETE RESTRICT,
    CONSTRAINT chk_monitoring_keyword_settlement_source
        CHECK (keyword_source IN ('confirmed', 'contract', 'extra')),
    CONSTRAINT chk_monitoring_keyword_settlement_state
        CHECK (state IN ('reserved', 'frozen', 'coverage_unknown',
                         'committed', 'released', 'admin_covered')),
    CONSTRAINT chk_monitoring_keyword_settlement_freeze
        CHECK (frozen_amount >= 0 AND freeze_table IS NULL
               OR frozen_amount >= 0 AND freeze_table IN ('legacy', 'v35'))
);

-- @index-guard idx_monitoring_keyword_settlement_reconcile ON monitoring_keyword_settlements plain
DO $idxguard$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_index i ON i.indexrelid = c.oid
                WHERE c.relname = 'idx_monitoring_keyword_settlement_reconcile' AND i.indrelid = to_regclass('public.monitoring_keyword_settlements')) THEN
        NULL;  -- 已在 public.monitoring_keyword_settlements 上 → 幂等跳过
    ELSIF EXISTS (SELECT 1 FROM pg_class c
                   WHERE c.relname = 'idx_monitoring_keyword_settlement_reconcile' AND c.relnamespace = 'public'::regnamespace) THEN
        RAISE EXCEPTION '[index-guard] idx_monitoring_keyword_settlement_reconcile 已存在但不在 public.monitoring_keyword_settlements 上(实际宿主:%)—— 拒绝静默跳过',
            (SELECT COALESCE(t.relname, 'relkind=' || c.relkind::text) FROM pg_class c
               LEFT JOIN pg_index i ON i.indexrelid = c.oid
               LEFT JOIN pg_class t ON t.oid = i.indrelid
              WHERE c.relname = 'idx_monitoring_keyword_settlement_reconcile' AND c.relnamespace = 'public'::regnamespace)
            USING ERRCODE = 'duplicate_object';
    ELSE
        CREATE INDEX idx_monitoring_keyword_settlement_reconcile ON public.monitoring_keyword_settlements (state, updated_at, settlement_reference);
    END IF;
END $idxguard$;

CREATE TABLE IF NOT EXISTS public.monitoring_cell_retry_requests (
    request_id UUID PRIMARY KEY,
    cell_id BIGINT NOT NULL,
    task_id INTEGER NOT NULL,
    brand_id INTEGER NOT NULL,
    plan_hash CHAR(64) NOT NULL,
    params_hash CHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'accepted',
    claim_token UUID,
    response_snapshot JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    CONSTRAINT fk_monitoring_cell_retry_requests_cell
        FOREIGN KEY (cell_id) REFERENCES public.monitoring_run_cells(id) ON DELETE RESTRICT,
    CONSTRAINT fk_monitoring_cell_retry_requests_task
        FOREIGN KEY (task_id) REFERENCES public.monitoring_tasks(id) ON DELETE RESTRICT,
    CONSTRAINT fk_monitoring_cell_retry_requests_brand
        FOREIGN KEY (brand_id) REFERENCES public.brands(id) ON DELETE RESTRICT,
    CONSTRAINT fk_monitoring_cell_retry_requests_scope
        FOREIGN KEY (cell_id, task_id, brand_id, plan_hash)
        REFERENCES public.monitoring_run_cells(id, task_id, brand_id, plan_hash)
        ON DELETE RESTRICT,
    CONSTRAINT chk_monitoring_cell_retry_requests_status
        CHECK (status IN ('accepted', 'running', 'succeeded', 'failed', 'blocked')),
    CONSTRAINT chk_monitoring_cell_retry_requests_lifecycle
        CHECK (
            (status = 'accepted' AND claim_token IS NULL AND completed_at IS NULL)
            OR (status = 'running' AND claim_token IS NOT NULL AND completed_at IS NULL)
            OR (status IN ('succeeded', 'failed', 'blocked')
                AND claim_token IS NOT NULL AND completed_at IS NOT NULL)
        ),
    CONSTRAINT chk_monitoring_cell_retry_requests_response
        CHECK (pg_catalog.jsonb_typeof(response_snapshot) = 'object')
);

-- @index-guard idx_monitoring_cell_retry_requests_cell ON monitoring_cell_retry_requests plain
DO $idxguard$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_index i ON i.indexrelid = c.oid
                WHERE c.relname = 'idx_monitoring_cell_retry_requests_cell' AND i.indrelid = to_regclass('public.monitoring_cell_retry_requests')) THEN
        NULL;  -- 已在 public.monitoring_cell_retry_requests 上 → 幂等跳过
    ELSIF EXISTS (SELECT 1 FROM pg_class c
                   WHERE c.relname = 'idx_monitoring_cell_retry_requests_cell' AND c.relnamespace = 'public'::regnamespace) THEN
        RAISE EXCEPTION '[index-guard] idx_monitoring_cell_retry_requests_cell 已存在但不在 public.monitoring_cell_retry_requests 上(实际宿主:%)—— 拒绝静默跳过',
            (SELECT COALESCE(t.relname, 'relkind=' || c.relkind::text) FROM pg_class c
               LEFT JOIN pg_index i ON i.indexrelid = c.oid
               LEFT JOIN pg_class t ON t.oid = i.indrelid
              WHERE c.relname = 'idx_monitoring_cell_retry_requests_cell' AND c.relnamespace = 'public'::regnamespace)
            USING ERRCODE = 'duplicate_object';
    ELSE
        CREATE INDEX idx_monitoring_cell_retry_requests_cell ON public.monitoring_cell_retry_requests (cell_id, created_at DESC);
    END IF;
END $idxguard$;

CREATE TABLE IF NOT EXISTS public.monitoring_provider_review_events (
    request_id UUID PRIMARY KEY,
    cell_id BIGINT NOT NULL,
    task_id INTEGER NOT NULL,
    brand_id INTEGER NOT NULL,
    plan_hash CHAR(64) NOT NULL,
    action VARCHAR(32) NOT NULL,
    actor_user_id INTEGER NOT NULL,
    note TEXT NOT NULL,
    state_before VARCHAR(40) NOT NULL,
    state_after VARCHAR(40) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_monitoring_provider_review_scope
        FOREIGN KEY (cell_id, task_id, brand_id, plan_hash)
        REFERENCES public.monitoring_run_cells(id, task_id, brand_id, plan_hash)
        ON DELETE RESTRICT,
    CONSTRAINT chk_monitoring_provider_review_action
        CHECK (action IN ('confirm_failed', 'confirm_unavailable')),
    CONSTRAINT chk_monitoring_provider_review_states
        CHECK (
            state_before = 'pending_provider_confirmation'
            AND state_after IN ('failed', 'unavailable')
        )
);

-- @index-guard idx_monitoring_provider_review_cell ON monitoring_provider_review_events plain
DO $idxguard$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_index i ON i.indexrelid = c.oid
                WHERE c.relname = 'idx_monitoring_provider_review_cell' AND i.indrelid = to_regclass('public.monitoring_provider_review_events')) THEN
        NULL;  -- 已在 public.monitoring_provider_review_events 上 → 幂等跳过
    ELSIF EXISTS (SELECT 1 FROM pg_class c
                   WHERE c.relname = 'idx_monitoring_provider_review_cell' AND c.relnamespace = 'public'::regnamespace) THEN
        RAISE EXCEPTION '[index-guard] idx_monitoring_provider_review_cell 已存在但不在 public.monitoring_provider_review_events 上(实际宿主:%)—— 拒绝静默跳过',
            (SELECT COALESCE(t.relname, 'relkind=' || c.relkind::text) FROM pg_class c
               LEFT JOIN pg_index i ON i.indexrelid = c.oid
               LEFT JOIN pg_class t ON t.oid = i.indrelid
              WHERE c.relname = 'idx_monitoring_provider_review_cell' AND c.relnamespace = 'public'::regnamespace)
            USING ERRCODE = 'duplicate_object';
    ELSE
        CREATE INDEX idx_monitoring_provider_review_cell ON public.monitoring_provider_review_events (cell_id, created_at DESC);
    END IF;
END $idxguard$;

CREATE OR REPLACE FUNCTION public.reject_monitoring_provider_review_event_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'monitoring provider review events are append-only';
END;
$$;

DROP TRIGGER IF EXISTS trg_monitoring_provider_review_events_append_only
    ON public.monitoring_provider_review_events;
CREATE TRIGGER trg_monitoring_provider_review_events_append_only
BEFORE UPDATE OR DELETE ON public.monitoring_provider_review_events
FOR EACH ROW EXECUTE FUNCTION public.reject_monitoring_provider_review_event_mutation();
DROP TRIGGER IF EXISTS trg_monitoring_provider_review_events_no_truncate
    ON public.monitoring_provider_review_events;
CREATE TRIGGER trg_monitoring_provider_review_events_no_truncate
BEFORE TRUNCATE ON public.monitoring_provider_review_events
FOR EACH STATEMENT EXECUTE FUNCTION public.reject_monitoring_provider_review_event_mutation();

CREATE OR REPLACE FUNCTION public.reject_monitoring_run_cell_terminal_overwrite()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF OLD.fulfillment_state IS DISTINCT FROM NEW.fulfillment_state
       AND NOT (
           (OLD.fulfillment_state = 'reserved'
            AND NEW.fulfillment_state IN ('covered', 'admin_covered', 'coverage_unknown', 'released'))
           OR (OLD.fulfillment_state = 'coverage_unknown'
               AND NEW.fulfillment_state IN ('covered', 'released'))
           OR (OLD.fulfillment_state = 'covered'
               AND NEW.fulfillment_state = 'released'
               AND EXISTS (
                   SELECT 1
                     FROM public.point_freezes pf
                     JOIN public.organization_charge_links charge
                       ON charge.physical_backend='legacy_user_wallet'
                      AND charge.physical_freeze_id=pf.id::text
                    WHERE pf.task_ref=OLD.settlement_reference
                      AND charge.status='refunded'
               ))
       ) THEN
        RAISE EXCEPTION 'monitoring cell fulfillment transition is invalid';
    END IF;
    IF OLD.state = 'succeeded'
       AND ROW(OLD.state, OLD.result_id, OLD.plan_hash, OLD.entitlement_snapshot,
               OLD.order_snapshot, OLD.fulfillment_credential)
           IS DISTINCT FROM
           ROW(NEW.state, NEW.result_id, NEW.plan_hash, NEW.entitlement_snapshot,
               NEW.order_snapshot, NEW.fulfillment_credential) THEN
        RAISE EXCEPTION 'successful monitoring cells are immutable';
    END IF;
    IF OLD.state = 'pending_identity'
       AND (
           NEW.state NOT IN ('pending_identity', 'succeeded')
           OR OLD.result_id IS DISTINCT FROM NEW.result_id
       ) THEN
        RAISE EXCEPTION 'pending identity monitoring cell transition is invalid';
    END IF;
    IF ROW(OLD.task_id, OLD.brand_id, OLD.keyword_id, OLD.keyword_source,
           OLD.quote_id, OLD.keyword_snapshot, OLD.question_snapshot,
           OLD.target_brand_snapshot, OLD.platform, OLD.is_planned,
           OLD.entitlement_snapshot, OLD.order_snapshot,
           OLD.fulfillment_credential, OLD.settlement_reference, OLD.plan_hash)
       IS DISTINCT FROM
       ROW(NEW.task_id, NEW.brand_id, NEW.keyword_id, NEW.keyword_source,
           NEW.quote_id, NEW.keyword_snapshot, NEW.question_snapshot,
           NEW.target_brand_snapshot, NEW.platform, NEW.is_planned,
           NEW.entitlement_snapshot, NEW.order_snapshot,
           NEW.fulfillment_credential, NEW.settlement_reference, NEW.plan_hash) THEN
        RAISE EXCEPTION 'monitoring cell plan is immutable';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_monitoring_run_cell_terminal_overwrite
    ON public.monitoring_run_cells;
CREATE TRIGGER trg_monitoring_run_cell_terminal_overwrite
BEFORE UPDATE ON public.monitoring_run_cells
FOR EACH ROW EXECUTE FUNCTION public.reject_monitoring_run_cell_terminal_overwrite();
