-- Throwaway/development rollback only. Never run against production without Deploy approval.
DROP TRIGGER IF EXISTS trg_dealer_fulfillment_hop_immutable ON dealer_resale_fulfillment_hops;
DROP TRIGGER IF EXISTS trg_dealer_fulfillment_plan_immutable ON dealer_resale_fulfillment_plans;
DROP FUNCTION IF EXISTS dealer_resale_fulfillment_hop_immutable_guard();
DROP FUNCTION IF EXISTS dealer_resale_fulfillment_plan_immutable_guard();
DROP TABLE IF EXISTS dealer_consumer_jit_refund_lots;
DROP TABLE IF EXISTS dealer_resale_hop_profit_ledger;
DROP TABLE IF EXISTS dealer_resale_hop_transfer_entries;
DROP TABLE IF EXISTS dealer_resale_fulfillment_allocations;
DROP TABLE IF EXISTS dealer_resale_fulfillment_hops;
DROP TABLE IF EXISTS dealer_resale_fulfillment_plans;
ALTER TABLE dealer_inventory_lots DROP CONSTRAINT IF EXISTS chk_dealer_lot_promotion_snapshot;
ALTER TABLE dealer_inventory_lots DROP CONSTRAINT IF EXISTS chk_dealer_lot_promotion_scope;
ALTER TABLE dealer_inventory_lots DROP CONSTRAINT IF EXISTS chk_dealer_lot_promotion_lineage_v2;
ALTER TABLE dealer_inventory_lots DROP CONSTRAINT IF EXISTS chk_dealer_lot_standard_reference;
ALTER TABLE dealer_inventory_lots DROP CONSTRAINT IF EXISTS chk_dealer_lot_jit_lineage;
DROP INDEX IF EXISTS idx_dealer_lot_promotion_fifo;
DROP INDEX IF EXISTS idx_dealer_lot_promotion_fifo_v2;
DROP INDEX IF EXISTS ux_dealer_lot_root_hop;
ALTER TABLE dealer_inventory_lots DROP COLUMN IF EXISTS promotion_snapshot_jsonb;
ALTER TABLE dealer_inventory_lots DROP COLUMN IF EXISTS promotion_funding_scope;
ALTER TABLE dealer_inventory_lots DROP COLUMN IF EXISTS promotion_campaign_id;
ALTER TABLE dealer_inventory_lots DROP COLUMN IF EXISTS promotion_product_code;
ALTER TABLE dealer_inventory_lots DROP COLUMN IF EXISTS promotion_root_catalog_version;
ALTER TABLE dealer_consumer_sales DROP CONSTRAINT IF EXISTS chk_dealer_consumer_sale_payout_v2;
ALTER TABLE dealer_consumer_sales DROP COLUMN IF EXISTS agent_payable_cents;
ALTER TABLE dealer_consumer_sales DROP COLUMN IF EXISTS principal_recovery_cents;
ALTER TABLE dealer_inventory_lots DROP COLUMN IF EXISTS standard_reference_cents;
ALTER TABLE dealer_inventory_lots DROP COLUMN IF EXISTS source_hop_seq;
ALTER TABLE dealer_inventory_lots DROP COLUMN IF EXISTS root_order_id;
DROP TABLE IF EXISTS dealer_resale_promotions;
